<a href="https://colab.research.google.com/github/Sridevi-coder62/Numpy-Calculations/blob/main/Numpy_Calculations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1.Normal Python List — Find the Middle Element(s)

Given a Python list of integers, find the middle element.

Requirements
If the list has an odd number of elements, return the single middle element.
If the list has an even number of elements, return the two middle elements.
Do not use NumPy.

Example 1

Input:
nums = [10, 20, 30, 40, 50]

Output:
30

Example 2
Input:
nums = [10, 20, 30, 40, 50, 60]

Output:
[30, 40]

Skills Tested
List indexing
len()
Integer division
Conditional statements

In [ ]:
nums=[10,20,30,40,50]

n=len(nums)

if n%2 == 0:
  print(nums[n//2], nums[n//2]-1)

else:
  print(nums[n//2])




30


In [ ]:
A= [23, 67, 12, 67, 66,90]

n=len(A)

if n%2==0:
  print(A[n//2],A[n//2]-1)
else:
  print(A[n//2])

67 66


2.NumPy 2D Array — Find Border Elements

Given a 2D NumPy array, extract all the elements present on the border of the matrix.

Example
Input:

[[1,  2,  3,  4],
 [5,  6,  7,  8],
 [9, 10, 11, 12],
 [13, 14, 15, 16]]

Output
[1, 2, 3, 4, 8, 12, 16, 15, 14, 13, 9, 5]

The output follows a clockwise traversal of the boundary.


Skills Tested
NumPy 2D indexing
Row/column indexing
Slicing
Array traversal

In [ ]:
import numpy as np
A= np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]])

top=A[0, :]

right=A[1:,-1]


bottom=A[-1,-2::-1]


left=A[-2:0:-1,0]

border=np.concatenate((top,right,bottom,left))
print(border)


[ 1  2  3  4  8 12 16 15 14 13  9  5]


3.Normal Python List — Move Zeros to the End

Given a list containing integers, move all 0s to the end while maintaining the relative order of non-zero elements.

Example
Input:

nums = [0, 1, 0, 3, 12]
Output
[1, 3, 12, 0, 0]
Another Example
Input:

nums = [4, 0, 5, 0, 2, 0, 8]
Output
[4, 5, 2, 8, 0, 0, 0]
Restrictions

Try solving it without using:

sort()
Skills Tested
List traversal
Index manipulation
Conditional logic
Maintaining element order

In [ ]:
Nums=[0,1,0,3,12]

result=[]

for n in Nums:
  if n!=0:
    result.append(n)

for n in Nums:
  if n==0:
    result.append(n)

print(result)

[1, 3, 12, 0, 0]


4.NumPy 2D Array — Rotate Matrix 90° Clockwise

Given a 2D NumPy array, rotate the matrix 90 degrees clockwise.

Input
[[1, 2, 3],
 [4, 5, 6],
 [7, 8, 9]]
Output
[[7, 4, 1],
 [8, 5, 2],
 [9, 6, 3]]

Another Example
Input:

[[1, 2],
 [3, 4],
 [5, 6]]
Output
[[5, 3, 1],
 [6, 4, 2]]

Skills Tested
2D indexing
Rows and columns
Transpose concepts
NumPy slicing
Matrix manipulation


In [ ]:
Input = np.array([[1,2,3],[4,5,6],[7,8,9]])

result=Input.T[:,::-1]
print(result)

[[7 4 1]
 [8 5 2]
 [9 6 3]]


5.Normal Python List — Find the First Repeating Element and Its Index

Given a list of integers, find the first element that appears more than once.

Return:

[element, first_index, repeated_index]

The element whose second occurrence appears earliest should be considered the answer.

Example
Input:

nums = [5, 3, 4, 3, 5, 4]

Output:

[3, 1, 3]

Because:

5 → appears again at index 4
3 → appears again at index 3
4 → appears again at index 5

The earliest repetition is 3 at index 3.

Another Example
Input:

nums = [10, 20, 30, 20, 10]

Output:

[20, 1, 3]

Additional Requirement

If no element is repeated:

Input:
[1, 2, 3, 4]

Output:
[-1, -1, -1]

Skills Tested
Index tracking
List traversal
Searching
Dictionary/set concepts
Understanding first occurrence vs repeated occurrence


In [16]:
nums=[10,20,30,20,10]

for i in range(len (nums)):

  if nums[i] in nums[:i]:
    print([nums[i],nums[:i].index(nums[i]), i])
    break
  else:
    print(-1,-1,-1)

-1 -1 -1
-1 -1 -1
-1 -1 -1
[20, 1, 3]


6. NumPy 3D Array — Find the Layer With the Highest Sum

You are given a 3D NumPy array representing multiple layers of data.

Your task is to:

Calculate the sum of every 2D layer.
Find the layer with the highest sum.
Return:
Layer index
Layer sum
The layer itself
Input
arr = np.array([
    [
        [1, 2],
        [3, 4]
    ],

    [
        [5, 6],
        [7, 8]
    ],

    [
        [2, 3],
        [1, 2]
    ]
])

Think of this as:

Layer 0

1  2
3  4

Sum = 10
Layer 1

5  6
7  8

Sum = 26
Layer 2

2  3
1  2

Sum = 8
Expected Output
Layer Index: 1

Layer Sum: 26

Layer:
[[5 6]
 [7 8]]

Skills Tested
3D NumPy indexing
Understanding dimensions
Axis-based operations
sum()
Finding maximum
Extracting a specific layer

In [17]:
A  = np.array([[[1,2],[3,4]],[[5,6],[7,8]],[[2,3],[1,2]]])

sums= A.sum(axis=(1,2))

index=np.argmax(sums)
print("Layer Index: ", index)
print("Layer Sum: ", sums[index])

print("Layers: ")
print(A[index])


Layer Index:  1
Layer Sum:  26
Layers: 
[[5 6]
 [7 8]]
